import { Setting } from '../../types/Levels';
import raisHandRight from '../../assets/raisHandRight.svg';
import turnRightHead from '../../assets/turnRightHead.svg';
import turnLeftHead from '../../assets/turnLeftHead.svg';
import lookLeft from '../../assets/lookLeft.svg';
import look from '../../assets/look.svg';
import lookRight from '../../assets/lookRight.svg';
import LookUpLeft from '../../assets/LookUpLeft.svg';
import LookUpRight from '../../assets/lookUpRight.svg';
import closeEyes from '../../assets/closeEyes.svg';
import raise60Right from '../../assets/raise60.svg';
import raise120Right from '../../assets/raise120.svg';
import raise60Left from '../../assets/raise60Left.svg';
import raise120Left from '../../assets/raiseleft120.svg';
export const settings_hard: Setting[] = [
  {
    settingName: 'Scorcha',
    settingImage: '/bgs/scorcha.svg',
    settingBg: '/bgs/scorcha-bg.svg',
    accessible: true,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Wake up Zappy!',
        reward: 100,
        gif: [look],
        hint: ['Normal Look'],
        correctCode: [{ eyes: '0' }],
        completed: true,
      },
      {
        levelNum: 2,
        goalTitle: 'Blink your worries away',
        reward: 100,
        gif: [closeEyes, look, closeEyes, look, closeEyes, look, closeEyes],
        hint: [
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
        ],
        correctCode: [
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
        ],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Stretch lightly',
        reward: 100,
        gif: [raise60Left, raise60Right],
        hint: ['Raise Left Arm 60°', 'Raise Right Arm 60°'],
        correctCode: [{ leftArm: '1' }, { rightArm: '1' }],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: 'Suspicious looks',
        reward: 120,
        gif: [turnLeftHead, lookRight, turnRightHead, lookLeft],
        hint: ['Head Turn Left', 'Look Right', 'Head Turn Right', 'Look Left'],
        correctCode: [
          { head: '1' },
          { eyes: 'c' },
          { head: '2' },
          { eyes: 'b' },
        ],
        completed: false,
      },
      {
        levelNum: 5,
        goalTitle: 'Arms forward, raise!',
        reward: 80,
        gif: [raise120Left, raise120Right],
        hint: ['Raise Left Arm 120°', 'Raise Right Arm 120°'],
        correctCode: [{ leftArm: '3' }, { rightArm: '3' }],
        completed: false,
      },
    ],
  },
  {
    settingName: 'Flora',
    settingImage: 'bgs/flora.svg',
    settingBg: 'bgs/flora-bg.svg',
    accessible: false,
    levels: [
      {
        levelNum: 1,
        goalTitle: "Too bright, can't see!",
        reward: 80,
        gif: [look, closeEyes, look, closeEyes, look, closeEyes],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
        ],
        completed: false,
      },
      {
        levelNum: 2,
        goalTitle: 'Stretch hard',
        reward: 80,
        gif: [closeEyes, raise120Left, raisHandRight],
        hint: ['Close Eyes', 'Raise Left Arm 120°', 'Raise Right Arm Fully'],
        correctCode: [{ eyes: 'i' }, { leftArm: '3' }, { rightArm: '3' }],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Twice on the right',
        reward: 70,
        gif: [turnRightHead, look, closeEyes, look, closeEyes],
        hint: [
          'Head Turn Right',
          'Normal Look',
          ' Close Eyes',
          'Normal Look',
          'Close Eyes',
        ],
        correctCode: [
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
        ],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: 'Nothing left',
        reward: 80,
        gif: [turnLeftHead, lookRight, LookUpRight, lookLeft, LookUpLeft],
        hint: [
          'Head Turn Left',
          'Look Right',
          'Look Upper Right',
          'Look Left',
          'Look Upper Left',
        ],
        correctCode: [
          { head: '1' },
          { eyes: 'c' },
          { eyes: 'f' },
          { eyes: 'b' },
          { eyes: 'e' },
        ],
        completed: false,
      },
      {
        levelNum: 5,
        goalTitle: 'Saw something',
        reward: 70,
        gif: [turnRightHead, raise60Left],
        hint: ['Head Turn', 'Raise Left Arm 60°'],
        correctCode: [{ head: '2' }, { leftArm: '2' }],
        completed: false,
      },
    ],
  },
  {
    settingName: 'Darka',
    settingImage: 'bgs/darka.svg',
    settingBg: 'bgs/darka-bg.svg',
    accessible: false,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          turnRightHead,
          turnLeftHead,
          turnRightHead,
          look,
          closeEyes,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Head Turn Right',
          'Head Turn Left',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { head: '2' },
          { head: '1' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
        ],
        completed: false,
      },
    ],
  },
  {
    settingName: 'Mistica',
    settingImage: 'bgs/mystica.svg',
    settingBg: 'bgs/mystica-bg.svg',
    accessible: false,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Wake up Zappy!',
        reward: 100,
        gif: [look],
        hint: ['Normal Look'],
        correctCode: [{ eyes: '0' }],
        completed: true,
      },
      {
        levelNum: 2,
        goalTitle: 'Blink your worries away',
        reward: 100,
        gif: [closeEyes, look, closeEyes, look, closeEyes, look, closeEyes],
        hint: [
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
        ],
        correctCode: [
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
        ],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Stretch lightly',
        reward: 100,
        gif: [raise60Left, raise60Right],
        hint: ['Raise Left Arm 60°', 'Raise Right Arm 60°'],
        correctCode: [{ leftArm: '1' }, { rightArm: '1' }],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: 'Suspicious looks',
        reward: 120,
        gif: [turnLeftHead, lookRight, turnRightHead, lookLeft],
        hint: ['Head Turn Left', 'Look Right', 'Head Turn right', 'Look Left'],
        correctCode: [
          { head: '1' },
          { eyes: 'c' },
          { head: '2' },
          { eyes: 'b' },
        ],
        completed: false,
      },
      {
        levelNum: 5,
        goalTitle: 'Arms forward, raise!',
        reward: 80,
        gif: [raise120Left, raise120Right],
        hint: ['Raise Left Arm 120°', 'Raise Right Arm 120°'],
        correctCode: [{ leftArm: '3' }, { rightArm: '3' }],
        completed: false,
      },
    ],
  },
  {
    settingName: 'Futura',
    settingImage: 'bgs/futura.svg',
    settingBg: 'bgs/futura-bg.svg',
    accessible: false,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Wake up Zappy!',
        reward: 100,
        gif: [look],
        hint: ['Normal Look'],
        correctCode: [{ eyes: '0' }],
        completed: true,
      },
      {
        levelNum: 2,
        goalTitle: 'Blink your worries away',
        reward: 100,
        gif: [closeEyes, look, closeEyes, look, closeEyes, look, closeEyes],
        hint: [
          'Close Eyes',
          'Normal Look',
          ' Close Eyes',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
        ],
        correctCode: [
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
        ],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Stretch lightly',
        reward: 100,
        gif: [raise60Left, raise60Right],
        hint: ['Raise Left Arm 60°', 'Raise Right Arm 60°'],
        correctCode: [{ leftArm: '1' }, { rightArm: '1' }],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: 'Suspicious looks',
        reward: 120,
        gif: [turnLeftHead, lookRight, turnRightHead, lookLeft],
        hint: ['Head Turn Left', 'Look Right', 'Head Turn Right', 'Look Left'],
        correctCode: [
          { head: '1' },
          { eyes: 'c' },
          { head: '2' },
          { eyes: 'b' },
        ],
        completed: false,
      },
      {
        levelNum: 5,
        goalTitle: 'Arms forward, raise!',
        reward: 80,
        gif: [raise120Left, raise120Right],
        hint: ['Raise Left Arm 120°', 'Raise Right Arm 120°  '],
        correctCode: [{ leftArm: '3' }, { rightArm: '3' }],
        completed: false,
      },
    ],
  },
];
