import { Setting } from '../../types/Levels';
import turnRightHead from '../../assets/turnRightHead.svg';
import turnLeftHead from '../../assets/turnLeftHead.svg';
import lookLeft from '../../assets/lookLeft.svg';
import look from '../../assets/look.svg';
import lookRight from '../../assets/lookRight.svg';
import LookUpLeft from '../../assets/LookUpLeft.svg';
import LookUpRight from '../../assets/lookUpRight.svg';
import closeEyes from '../../assets/closeEyes.svg';
import raise60Right from '../../assets/raise60.svg';
import raise60Left from '../../assets/raise60Left.svg';

export const settings_easy: Setting[] = [
  {
    settingName: 'Scorcha',
    settingImage: '/bgs/scorcha.svg',
    settingBg: '/bgs/scorcha-bg.svg',
    accessible: true,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Top of the morning!',
        reward: 100,
        gif: [look],
        hint: ['Normal Look'],
        correctCode: [{ eyes: '0' }],
        completed: true,
      },
      {
        levelNum: 2,
        goalTitle: 'Blink your worries away',
        reward: 80,
        gif: [closeEyes, look, closeEyes, look],
        hint: ['Close Eyes', 'Normal Look', 'Close Eyes', 'Normal Look'],
        correctCode: [
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
        ],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Where are you?',
        reward: 80,
        gif: [lookLeft, lookRight],
        hint: ['Look  Left', 'Look Right'],
        correctCode: [{ eyes: 'b' }, { eyes: 'c' }],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: 'Do you hear anything?',
        reward: 80,
        gif: [LookUpLeft, LookUpRight],
        hint: ['Look Upper Left', 'Look Upper Right'],
        correctCode: [{ eyes: 'e' }, { eyes: 'f' }],
        completed: false,
      },
      {
        levelNum: 5,
        goalTitle: 'Stretch lightly',
        reward: 100,
        gif: [raise60Left, raise60Right],
        hint: ['Raise Left Arm 60°', 'Raise Right Arm 60°'],
        correctCode: [{ leftArm: '1' }, { rightArm: '1' }],
        completed: false,
      },
    ],
  },
  {
    settingName: 'Flora',
    settingImage: 'bgs/flora.svg',
    settingBg: 'bgs/flora-bg.svg',
    accessible: false,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Too bright',
        reward: 100,
        gif: [closeEyes, look, closeEyes, look, closeEyes],
        hint: [
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
          ' Normal Look',
          'Close Eyes',
        ],
        correctCode: [
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { eyes: 'i' },
        ],
        completed: true,
      },
      {
        levelNum: 2,
        goalTitle: 'Look for people',
        reward: 80,
        gif: [look, lookRight, LookUpRight, lookLeft, LookUpLeft],
        hint: [
          'Normal Look',
          'Look Right',
          'Look Upper Right',
          'Look Left',
          'Look Upper Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'c' },
          { eyes: 'f' },
          { eyes: 'b' },
          { eyes: 'e' },
        ],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Right away',
        reward: 100,
        gif: [turnRightHead],
        hint: ['Head Turn Right'],
        correctCode: [{ head: '2' }],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: "Can't left",
        reward: 80,
        gif: [turnLeftHead],
        hint: ['Head Turn Left'],
        correctCode: [{ head: '1' }],
        completed: false,
      },
      {
        levelNum: 5,
        goalTitle: 'Heard something?',
        reward: 100,
        gif: [turnRightHead, lookRight],
        hint: ['Head Turn Right', 'Look Right'],
        correctCode: [{ head: '2' }, { eyes: 'c' }],
        completed: false,
      },
    ],
  },
  {
    settingName: 'Darka',
    settingImage: 'bgs/darka.svg',
    settingBg: 'bgs/darka-bg.svg',
    accessible: false,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: true,
      },
      {
        levelNum: 2,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
    ],
  },
  {
    settingName: 'Mistica',
    settingImage: 'bgs/mystica.svg',
    settingBg: 'bgs/mystica-bg.svg',
    accessible: false,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: true,
      },
      {
        levelNum: 2,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          ' Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          ' Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
    ],
  },
  {
    settingName: 'Futura',
    settingImage: 'bgs/futura.svg',
    settingBg: 'bgs/futura-bg.svg',
    accessible: false,
    levels: [
      {
        levelNum: 1,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: true,
      },
      {
        levelNum: 2,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
      {
        levelNum: 3,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Right',
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
      {
        levelNum: 4,
        goalTitle: 'Explore the meadow',
        reward: 150,
        gif: [
          look,
          closeEyes,
          look,
          turnRightHead,
          look,
          closeEyes,
          look,
          turnLeftHead,
        ],
        hint: [
          'Normal Look',
          'Close Eyes',
          'Normal Look',
          'Close Eyes',
          'Head Turn Right',
          'Normal Eyes',
          'Close Eyes',
          'Normal Eyes',
          'Head Turn Left',
        ],
        correctCode: [
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '2' },
          { eyes: '0' },
          { eyes: 'i' },
          { eyes: '0' },
          { head: '1' },
        ],
        completed: false,
      },
    ],
  },
];
